services:
  web:
    image: caddy:latest
    container_name: caddy_demo
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

    volumes:
      - ./public:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
volumes:
  caddy_data:
  caddy_config:
